### ISSUE TITLE
Issue when changing address in 2_deploy_contract.js

### ISSUE THREAD

**Issue by commentors-net** [paxosglobal/pax-contracts#16]
Hi,
I am trying to understand the proxy in ethererum and I found your contract is wonderful in order to understand.
Being a beginner I forked your repository for learning.
Everything works perfect when testing it will local ganache-cli, however I fail to deploy contract in ropsten when I change address file 2_deploy_contract.js
at line number 10 
from 
`await proxy.changeAdmin("0xf0b1eef88956b0a307fa87b5f5671aad6a5d330f");`

to
`await proxy.changeAdmin("0x79a28044af136e7aeccc0783e92fa07f2aef2e5c");`

Once this is done, the next line 
`await proxiedPAX.initialize();`

throw an exception

`RuntimeError: VM Exception while processing transaction: revert Cannot call fallback function from the proxy admin
    at module.exports (/home/vmware/Development/Ethereum/pax-contracts/migrations/2_deploy_contracts.js:11:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.1.34 (core: 5.1.34)
Node v10.16.3
`

If I don't change then I can't freeze any address.

If you can provide some information, then it will be great.
Thank you.

**Comment by commentors-net** [comment]
Manage to figure out that deployer and admin address can't be same. This is working now, however when change is made in Contract and truffle migrate is called, I get Network up to date, hence no upgrade take place.
